# .github/workflows/test.yml
name: Test

on:
  push:
    branches:
      - main
      - ci-testing
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.203'
        
    - name: Restore dependencies
      run: dotnet restore Tests/Tests.csproj
      
    - name: Test
      run: dotnet test --configuration Release --no-build Tests/Tests.csproj

